---
deployment:
  tasks:
    - chmod 755 ~/repositories
    - chmod 755 ~/repositories/laravel
    - chmod 755 ~/repositories/laravel/public
    - /opt/cpanel/composer/bin/composer update --optimize-autoloader --no-dev
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan view:cache
    - /usr/local/bin/php artisan route:cache